/**
 * Replaces the original CDN video background. Everything here is generated by
 * CSS — no third-party footage, image, or texture is downloaded, so there is
 * nothing to license. See LICENSES.md.
 */
export function Backdrop() {
  return (
    <div className="absolute inset-0 z-0 overflow-hidden bg-background" aria-hidden="true">
      <div className="backdrop-drift absolute inset-[-20%]" />
      <div className="backdrop-grain absolute inset-0" />
      <div className="absolute inset-0 bg-gradient-to-b from-black/40 via-transparent to-black/60" />
    </div>
  );
}
